services:
  frontend:
    hostname: frontend
    image: node:24
    working_dir: /app
    depends_on:
      - backend
    expose:
      - 5173
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - arcor_node_modules:/app/node_modules
    networks:
      - internal
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    command: bash -c 'npm install && npm run dev --host'
  backend:
    image: python:3.13.3
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "pip install -r requirements.txt &&
      uvicorn api:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    expose:
      - 8000
    networks:
      - internal
volumes:
  arcor_node_modules:
  
networks:
  internal:
